MvcProjeKampi/Controllers/vitrinController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    [AllowAnonymous]
    public class vitrinController : Controller
    {
        // GET: vitrin

        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        ContentManager cm = new ContentManager(new EfContentDal());

        public ActionResult Headings()
        {
            var headingList = hm.GetList();
            
            
            return View(headingList);
        }
        public PartialViewResult Index(int id=0)
        {
            var values = cm.GetListById(id);
            return PartialView(values);
        }
    }
}

MvcProjeKampi/Views/vitrin/Headings.cshtml
@using EntityLayer.Concrete
@model List<Heading>

@{
    Layout = null;
}


<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>Kullanıcı Paneli</title>

    <!-- summernote -->
    <link rel="stylesheet" href="~/webAdmin/plugins/summernote/summernote-bs4.css">

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/webAdmin/plugins/fontawesome-free/css/all.min.css">
    <!-- IonIcons -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/webAdmin/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to to the body tag
to get the desired effect
|---------------------------------------------------------|
|LAYOUT OPTIONS | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a class="nav-link">Kullanıcı Paneli</a>
                </li>

                

            </ul>




        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="http://linktr.ee/budotekno" class="brand-link">
                <img src="~/webAdmin/dist/img/Logo.png" alt="Budotekno Logo"
                     width="50" style="margin-left:5px">
                <span class="brand-text font-weight-light">Budotekno</span>
            </a>

            
            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional)
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/webAdmin/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">Alexander Pierce</a>
            </div>
        </div>
            -->
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">


                        <li class="nav-item">
                            <a href="/AdminLogin/Index" target="_blank" class="nav-link ">

                                <p>
                                    Admin Panel
                                </p>


                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="/AdminLogin/writerLogin/" target="_blank" class="nav-link">

                                <p>
                                    Yazar Panel
                                </p>


                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="/Home/HomePage/" target="_blank" class="nav-link border-bottom">

                                <p>
                                    Siteye Git
                                </p>


                            </a>
                        </li>





                        @foreach (var i in Model)
                        {
                            if (i.HeadingStatus==true)
                            {
                                

                                <li class="nav-item">
                                    <a href="/vitrin/Headings/@i.HeadingId/" class="nav-link">
                                        @if (i.HeadingName.Length > 20)
                                        {
                                        <p>
                                            @i.HeadingName.Substring(0, 20) <span>...</span>
                                        </p>
                                        }
                                        else
                                        {
                                    <p>
                                        @i.HeadingName.Substring(0, i.HeadingName.Length) 
                                    </p>
                                        }

                                    </a>
                                </li>
                            }

                        }





                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

            @Html.Action("Index","vitrin")

            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                  
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <strong>Bu site <a href="http://linktr.ee/budotekno">Budotekno</a> tarafından yapılmıştır.</strong>

            <div class="float-right d-none d-sm-inline-block">
                <b>Copyright &copy; @DateTime.Today.Year </b>
            </div>
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery --
    <script src="~/webAdmin/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/webAdmin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE -->
    <script src="~/webAdmin/dist/js/adminlte.js"></script>

    <!-- OPTIONAL SCRIPTS -->
    <script src="~/webAdmin/plugins/chart.js/Chart.min.js"></script>
    <script src="~/webAdmin/dist/js/demo.js"></script>
    <script src="~/webAdmin/dist/js/pages/dashboard3.js"></script>

    <!-- Summernote -->
    <script src="~/webAdmin/plugins/summernote/summernote-bs4.min.js"></script>


    <script src="~/webAdmin/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- Page Script -->
    <script>
        $(function () {
            //Add text editor
            $('#compose-textarea').summernote().noConflict;
        })
    </script>


</body>
</html>

MvcProjeKampi/Views/vitrin/Index.cshtml
@using EntityLayer.Concrete
@model List<Content>



<br />
<div class="container">

    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

               
                @if (Model.Count==0)
                {
                    <div class="alert alert-danger">
                        İlgili başlığa yazı yazılmamıştır !
                    </div>
                }
                
                

                <!-- Timelime example  -->
                @foreach (var i in Model)
                {
                   
                    <div class="row">
                        <div class="col-md-12">
                            <!-- The time line -->
                            <div class="timeline">
                                <!-- timeline time label -->
                                <div class="time-label">
                                    <span class="bg-success">@i.Writer.WriterName @i.Writer.WriterSurname  - @i.ContentDate.ToShortDateString()</span>
                                </div>
                                <!-- /.timeline-label -->
                                <!-- timeline item -->
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@i.Heading.HeadingName </a> </h3>
                                        <div class="timeline-body">
                                            @i.ContentValue
                                        </div>
                                    </div>
                                </div>
                                <!-- END timeline item -->
                            </div>
                        </div>
                        <!-- /.col -->
                    </div>



                }

            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->


</div>

