MvcProjeKampi/Controllers/AdminContactController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class AdminContactController : Controller
    {
        ContactManager cm = new ContactManager(new EfContactDal());
       

        ContactValidator cv = new ContactValidator();

        // GET: AdminContact
        public ActionResult Index()
        {
            var values = cm.GetList().OrderByDescending(x=>x.ContactId).ToList();
            return View(values);
        }

        public ActionResult GetContactDetail(int id)
        {
            var values = cm.GetById(id);
            return View(values);
        }

        MessageManager mm = new MessageManager(new EfMessageDal());


        public PartialViewResult MessageListMenu()
        {
            string p = (string)Session["WriterMail"];

            var valuesContactCount = cm.GetList().Count();
            ViewBag.valuesContactCount = valuesContactCount;

            var valuesInboxCount = mm.GetListInbox(false,p).Count();
            ViewBag.valuesInboxCount = valuesInboxCount;

            var valuesOkunmamisCount = mm.GetListInbox(true,p).Count();
            ViewBag.valuesOkunmamisCount = valuesOkunmamisCount;

            var valuesSenboxCount = mm.GetListSendbox(p).Count();
            ViewBag.valuesSenboxCount = valuesSenboxCount;



            return PartialView();
        }
    }
}

MvcProjeKampi/Controllers/AdminMessageController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class AdminMessageController : Controller
    {
        MessageManager mm = new MessageManager(new EfMessageDal());

        MessageValidator mv = new MessageValidator();


        // GET: Message
        public ActionResult Inbox()
        {
            string p = (string)Session["WriterMail"];

            var valuesCount = mm.GetListInbox(false,p).Count();
            ViewBag.valuesCount = valuesCount;
            var values = mm.GetListInbox(false,p);
            return View(values);
        }

        public ActionResult Sendbox()
        {
            string p = (string)Session["WriterMail"];
            var values = mm.GetListSendbox(p);
            return View(values);
        }

        public ActionResult GetInboxMessageDetails(int id)
        {
            var values = mm.GetById(id);
            return View(values);
        }

        public ActionResult GetOkunmamisMessageDetails(int id)
        {
           

            var values = mm.GetById(id);
            GetOkunmamisMessage(values);
            return View(values);
        }

        public void GetOkunmamisMessage(Message p)
        {


            p.Status = false;
            mm.UpdateMessage(p);
            
        }


        public ActionResult GetSendMessageDetails(int id)
        {
            var values = mm.GetById(id);
            return View(values);
        }

        public ActionResult OkunmamisMesaj()
        {
            string p = (string)Session["WriterMail"];

            var valuesCount = mm.GetListInbox(true,p).Count();
            ViewBag.valuesCount = valuesCount;
            var values = mm.GetListInbox(true,p);
            return View(values);
        }



        [HttpGet]
        public ActionResult NewMessage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NewMessage(Message p)
        {
            string a = (string)Session["WriterMail"];

            ValidationResult validationResult = mv.Validate(p);
            if (validationResult.IsValid)
            {
                p.SenderMail = a;
                p.Date = DateTime.Parse(DateTime.Now.ToShortDateString());
                mm.AddMessage(p);
                return RedirectToAction("Sendbox");

            }
            else
            {
                foreach (var i in validationResult.Errors)
                {
                    ModelState.AddModelError(i.PropertyName, i.ErrorMessage);
                }
            }
          

            return View();
        }
    }
}

MvcProjeKampi/Views/AdminMessage/GetInboxMessageDetails.cshtml
@model EntityLayer.Concrete.Message


@{
    ViewBag.Title = "GetInboxMessageDetails";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>İletişim & Mesaj</h1>
            </div>

        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">

            @Html.Action("MessageListMenu", "AdminContact")


            <div class="col-md-9">
                <div class="card card-primary card-outline">

                    <div class="card-header">
                        <h3 class="card-title">Mesaj İçeriği</h3>
                        <div class="card-tools">
                            <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                            <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-read-info">
                            <h5><b>Konu : </b> @Html.ValueFor(x => x.Subject) </h5>
                            <h6>
                                <b>Kimden : </b> @Html.ValueFor(x=>x.SenderMail)
                            <span class="mailbox-read-time float-right"> @Html.ValueFor(x => x.Date)   </span>
                            </h6>
                        </div>
                      
                        <div class="mailbox-read-message">
                            <p> <b>Mesaj : </b> @Html.ValueFor(x => x.Content)</p>
                        </div>
                        <!-- /.mailbox-read-message -->
                    </div>
                    <!-- /.card-footer -->



                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
</section>

MvcProjeKampi/Views/AdminMessage/GetOkunmamisMessageDetails.cshtml

@model EntityLayer.Concrete.Message



@{
    ViewBag.Title = "GetOkunmamisMessageDetails";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}




<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>İletişim & Mesaj</h1>
            </div>

        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">

            @Html.Action("MessageListMenu", "AdminContact")


            <div class="col-md-9">
                <div class="card card-primary card-outline">

                    <div class="card-header">
                        <h3 class="card-title">Mesaj İçeriği</h3>
                        <div class="card-tools">
                            <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                            <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-read-info">
                            <h5><b>Konu : </b> @Html.ValueFor(x => x.Subject) </h5>
                            <h6>
                                <b>Kimden : </b> @Html.ValueFor(x => x.SenderMail)
                                <span class="mailbox-read-time float-right"> @Html.ValueFor(x => x.Date)   </span>
                            </h6>
                        </div>

                        <div class="mailbox-read-message">
                            <p> <b>Mesaj : </b> @Html.ValueFor(x => x.Content)</p>
                        </div>
                        <!-- /.mailbox-read-message -->
                    </div>
                    <!-- /.card-footer -->



                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
</section>

MvcProjeKampi/Views/AdminMessage/GetSendMessageDetails.cshtml
@model EntityLayer.Concrete.Message

@{
    ViewBag.Title = "GetSendMessageDetails";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>İletişim & Mesaj</h1>
            </div>

        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">

            @Html.Action("MessageListMenu", "AdminContact")


            <div class="col-md-9">
                <div class="card card-primary card-outline">

                    <div class="card-header">
                        <h3 class="card-title">Mesaj İçeriği</h3>
                        <div class="card-tools">
                            <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                            <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-read-info">
                            <h5><b>Konu : </b> @Html.ValueFor(x => x.Subject) </h5>
                            <h6>
                                <b>Alıcı : </b> @Html.ValueFor(x => x.ReceiverMail)
                                <span class="mailbox-read-time float-right"> @Html.ValueFor(x => x.Date)   </span>
                            </h6>
                        </div>

                        <div class="mailbox-read-message">
                            <p> <b>Mesaj : </b> @Html.ValueFor(x => x.Content)</p>
                        </div>
                        <!-- /.mailbox-read-message -->
                    </div>
                    <!-- /.card-footer -->



                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
</section>

MvcProjeKampi/Views/AdminMessage/Inbox.cshtml
@using EntityLayer.Concrete
@model List<Message>

@{
    ViewBag.Title = "Inbox";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>İletişim & Mesaj</h1>
            </div>

        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="row">


        @Html.Action("MessageListMenu", "AdminContact")

        <!-- /.col -->
        <div class="col-md-9">
            <div class="card card-primary card-outline">
                <div class="card-header">
                    <h3 class="card-title">Gelen Kutusu</h3>

                    <div class="card-tools">
                        <div class="input-group input-group-sm">
                            <input type="text" class="form-control" placeholder="Mail Kutusunda Ara">
                            <div class="input-group-append">
                                <div class="btn btn-primary">
                                    <i class="fas fa-search"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-tools -->
                </div>
                <!-- /.card-header -->
                <div class="card-body p-0">
                    <div class="mailbox-controls">
                        <!-- Check all button -->
                        <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                            <i class="far fa-square"></i>
                        </button>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                        </div>
                        <!-- /.btn-group -->
                        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                        <div class="float-right">
                            1-50/200
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                            </div>
                            <!-- /.btn-group -->
                        </div>
                        <!-- /.float-right -->
                    </div>
                    <div class="table-responsive mailbox-messages">
                        <table class="table table-hover table-striped">
                            <tbody>
                                @foreach (var i in Model)
                                {
                                    <tr>
                                        <td>
                                            <div class="icheck-primary">
                                                <input type="checkbox" value="" id="check1">
                                                <label for="check1"></label>
                                            </div>
                                        </td>

                                        <td class="mailbox-star"><a><i class="fas fa-star text-warning"></i></a></td>
                                        <td class="mailbox-name"><a href="/AdminMessage/GetInboxMessageDetails/@i.MessageId/">@i.SenderMail</a></td>
                                        <td class="mailbox-subject">
                                            <b>@i.Subject</b> -
                                            <span>
                                                @if (i.Content.Length < 35)
                                                {
                                                    @i.Content.Substring(0, i.Content.Length);
                                                }
                                                else
                                                {

                                                    @i.Content.Substring(0, 35);<span>...</span>
                                                }

                                            </span>

                                        </td>
                                        <td class="mailbox-attachment"></td>
                                        <td class="mailbox-date"> @i.Date.ToShortDateString() </td>
                                    </tr>
                                }


                            </tbody>
                        </table>
                        <!-- /.table -->
                    </div>
                    <!-- /.mail-box-messages -->
                </div>
                <!-- /.card-body -->
                <div class="card-footer p-0">
                    <div class="mailbox-controls">
                        <!-- Check all button -->
                        <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                            <i class="far fa-square"></i>
                        </button>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                        </div>
                        <!-- /.btn-group -->
                        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                        <div class="float-right">
                            1-50/200
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                            </div>
                            <!-- /.btn-group -->
                        </div>
                        <!-- /.float-right -->
                    </div>
                </div>
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->









<script>
    $(function () {
        //Enable check and uncheck all functionality
        $('.checkbox-toggle').click(function () {
            var clicks = $(this).data('clicks')
            if (clicks) {
                //Uncheck all checkboxes
                $('.mailbox-messages input[type=\'checkbox\']').prop('checked', false)
                $('.checkbox-toggle .far.fa-check-square').removeClass('fa-check-square').addClass('fa-square')
            } else {
                //Check all checkboxes
                $('.mailbox-messages input[type=\'checkbox\']').prop('checked', true)
                $('.checkbox-toggle .far.fa-square').removeClass('fa-square').addClass('fa-check-square')
            }
            $(this).data('clicks', !clicks)
        })

        //Handle starring for glyphicon and font awesome
        $('.mailbox-star').click(function (e) {
            e.preventDefault()
            //detect type
            var $this = $(this).find('a > i')
            var glyph = $this.hasClass('glyphicon')
            var fa = $this.hasClass('fa')

            //Switch states
            if (glyph) {
                $this.toggleClass('glyphicon-star')
                $this.toggleClass('glyphicon-star-empty')
            }

            if (fa) {
                $this.toggleClass('fa-star')
                $this.toggleClass('fa-star-o')
            }
        })
    })</script>
<!-- AdminLTE for demo purposes -->
<script src="../../dist/js/demo.js"></script>

MvcProjeKampi/Views/AdminMessage/NewMessage.cshtml
@model EntityLayer.Concrete.Message

@{
    ViewBag.Title = "NewMessage";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>İletişim & Mesaj</h1>
                        </div>
                       
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                  

                        @Html.Action("MessageListMenu","AdminContact") 

                        <div class="col-md-9">
                            <div class="card card-primary card-outline">

                                <form action="/AdminMessage/NewMessage/" class="form-group" method="post">
                                    <div class="card-header">
                                        <h3 class="card-title">Mesaj Gönder</h3>
                                    </div>
                                    <!-- /.card-header -->
                                    <div class="card-body">
                                        <div class="form-group">
                                            <input class="form-control" name="Status" value="True" hidden>
                                        </div>
                                        <div class="form-group" hidden>
                                            <input class="form-control" name="SenderMail" placeholder="Gönderen :">
                                            @Html.ValidationMessageFor(x => x.SenderMail)
                                        </div>
                                        <div class="form-group">
                                            <input class="form-control" name="ReceiverMail" placeholder="Alıcı :">
                                            @Html.ValidationMessageFor(x => x.ReceiverMail)
                                        </div>
                                        <div class="form-group">
                                            <input class="form-control" name="Subject" placeholder="Konu :">
                                            @Html.ValidationMessageFor(x => x.Subject)
                                        </div>
                                        <div class="form-group">
                                            <textarea id="compose-textarea" name="Content" class="form-control" style="height: 300px"> </textarea>
                                            @Html.ValidationMessageFor(x => x.Content)
                                        </div>
                                        <div class="form-group">
                                            <div class="btn btn-default btn-file">
                                                <i class="fas fa-paperclip"></i> Dosya Ekle
                                                <input type="file">
                                            </div>
                                            <p class="help-block">Max. 32MB</p>
                                        </div>
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        <div class="float-right">
                                            <button type="button" class="btn btn-default"><i class="fas fa-pencil-alt"></i> Taslaklara Kaydet</button>
                                            <button type="submit" class="btn btn-primary"><i class="far fa-envelope"></i> Gönder</button>
                                        </div>
                                        <a href="/AdminContact/Index/" class="btn btn-danger"><i class="fas fa-times"></i> İptal</a>
                                    </div>
                                    <!-- /.card-footer -->

                                </form>
                            </div>
                            <!-- /.card -->
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
      