MvcProjeKampi/Controllers/AdminContentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class AdminContentController : Controller
    {
        ContentManager cm = new ContentManager(new EfContentDal());

        // GET: AdminContent
        public ActionResult Index(int id)
        {
            var values = cm.GetListById(id);
            return View(values);
        }

       // Context c = new Context();
        public ActionResult GettAllContent(string p="")
        {
            //   var values = from x in c.Contents select x;
            var values = cm.GetList(p);
            /*
            if (!string.IsNullOrEmpty(p))
            {
                values = values.Where(y => y.ContentValue.Contains(p));
            }*/
           // var values =c.Contents.ToList();
            return View(values);
        }
    }
}

MvcProjeKampi/Views/AdminContent/GettAllContent.cshtml
@using EntityLayer.Concrete
@model List<Content>

@{
    ViewBag.Title = "GettAllContent";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h3>Yazılar Listesi</h3>
<br />
<br />

<div class="container">

    @using (Html.BeginForm("GettAllContent", "AdminContent", FormMethod.Post))
    {
        <div class="row">
            <div class="col-md-4">
            </div>

            <div class="col-md-8">
                <div class="row">

                    <div class="col-md-8">
                        <input type="text" placeholder="Aranacak Kelimeyi Giriniz :" class="form-control" name="p" />

                    </div>
                    <div class="col-md-4">

                        <input type="submit" value="Ara" class="btn btn-secondary" />
                    </div>
                </div>
            </div>
        </div>
        <br />

    }
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Yazılar</th>

            </tr>
        </thead>
        <tbody>
            @{int i = 1; }
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@i</th>
                    <td>@item.ContentValue</td>
                </tr>
                i++;
            }

        </tbody>
    </table>




</div>


MvcProjeKampi/Views/AdminContent/Index.cshtml
@using EntityLayer.Concrete
@model List<Content> 

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<br />
<h3>Yazılar Listesi</h3>
<br />
<br />
<div class="container">

    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Timelime example  -->
                @foreach (var i in Model)
                {
                    <div class="row">
                        <div class="col-md-12">
                            <!-- The time line -->
                            <div class="timeline">
                                <!-- timeline time label -->
                                <div class="time-label">
                                    <span class="bg-success">@i.ContentDate.ToShortDateString()</span>
                                </div>
                                <!-- /.timeline-label -->
                                <!-- timeline item -->
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@i.Writer.WriterName @i.Writer.WriterSurname </a> </h3>
                                        <div class="timeline-body">
                                                @i.ContentValue
                                        </div>
                                    </div>
                                </div>
                                <!-- END timeline item -->
                            </div>
                        </div>
                        <!-- /.col -->
                    </div>
                }

            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->


</div>
